version: '3.8'
services:
  service-db:
    image: postgres:14.7-alpine
    env_file:
      - database.env
    ports:
      - "15432:5432"
    volumes:
      - ./sql/create_db.sql:/docker-entrypoint-initdb.d/create_db.sql
    restart: unless-stopped