server:
  port: 8080
spring:
  application:
    name: backend
  datasource:
    password: admin
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15432}/journey_db
    username: postgres
  liquibase:
    enabled: true
    drop-first: false
    change-log: classpath:db/changelog/db.changelog-master.xml
    default-schema: public
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
